In [3]:
import numpy as np

In [4]:
a = np.array([12, 55, 75, 2, 3])

In [5]:
a

array([12, 55, 75,  2,  3])

In [6]:
a.mean()

29.4

In [7]:
a.max()

75

In [8]:
a.sum()

147

In [9]:
a.min()

2

In [10]:
a.std()

29.950626036862733

In [11]:
a.prod()

297000

In [12]:
a.transpose()

array([12, 55, 75,  2,  3])

In [13]:
b = a.copy() #em python vc precisa 

In [14]:
b #

array([12, 55, 75,  2,  3])